# Generated by Django 3.2 on 2021-05-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_atcuser_pilotuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atcuser',
            options={'permissions': [('view_flight_detail', 'can view the flight detail page'), ('view_airline_detail', 'can view the airline detail page')]},
        ),
        migrations.AlterModelOptions(
            name='pilotuser',
            options={'permissions': [('view_pilot_detail', 'can view the pilot detail page'), ('view_airline_detail', 'can view the airline detail page')]},
        ),
    ]
