# Generated by Django 3.2 on 2021-04-28 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('aircraft_name', models.CharField(max_length=100)),
                ('aircraft_company', models.CharField(max_length=100)),
                ('aircraft_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('airline_name', models.CharField(max_length=100, unique=True)),
                ('airline_emp_count', models.IntegerField()),
                ('airline_flight_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('flight_source', models.CharField(max_length=50)),
                ('flight_destination', models.CharField(max_length=50)),
                ('flight_arrival', models.TimeField(blank=True, null=True)),
                ('flight_departure', models.TimeField(blank=True, null=True)),
                ('flight_delay', models.IntegerField(default=0)),
                ('flight_gate', models.IntegerField()),
                ('flight_crew_A', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_crew_B', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_crew_C', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.aircraft')),
                ('flight_airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('pilot_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pilot_name', models.CharField(max_length=100)),
                ('pilot_sex', models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F'), ('OTHERS', 'OTHER')], default='not found', max_length=10)),
                ('pilot_contact', models.BigIntegerField(default=0, null=True)),
                ('pilot_age', models.IntegerField(default=0)),
                ('pilot_aircraft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.aircraft')),
                ('pilot_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.airline')),
            ],
        ),
        migrations.CreateModel(
            name='PilotRoster',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('job_day', models.CharField(blank=True, max_length=20, null=True)),
                ('job_flight', models.ManyToManyField(to='manager.Flight')),
                ('job_pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.pilot')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.pilot'),
        ),
    ]
