# Generated by Django 3.2 on 2021-04-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_crew_A',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_crew_B',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_crew_C',
        ),
    ]
