# Generated by Django 3.2 on 2021-04-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210428_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_crew_A',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_crew_B',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_crew_C',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
