# Generated by Django 3.2 on 2021-04-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20210428_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_crew_A',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_crew_B',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_crew_C',
        ),
        migrations.CreateModel(
            name='GroundStaff',
            fields=[
                ('ground_staff_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ground_staff_name', models.CharField(max_length=50)),
                ('ground_staff_age', models.IntegerField()),
                ('ground_staff_contact', models.BigIntegerField()),
                ('ground_staff_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.airline')),
            ],
        ),
        migrations.CreateModel(
            name='CrewMembers',
            fields=[
                ('crew_member_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('crew_member_name', models.CharField(max_length=50)),
                ('crew_member_age', models.IntegerField()),
                ('crew_member_contact', models.BigIntegerField()),
                ('crew_member_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.airline')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_crew_members',
            field=models.ManyToManyField(to='manager.CrewMembers'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_ground_staff',
            field=models.ManyToManyField(to='manager.GroundStaff'),
        ),
    ]
