# Generated by Django 3.2 on 2021-05-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210428_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_fuel_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(choices=[('CARGO', 'Cargo'), ('PASSENGER', 'Passenger'), ('PRIVATE', 'Private')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
