# Generated by Django 3.2 on 2021-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20210502_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='pilot_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilot',
            name='pilot_designation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilot',
            name='pilot_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilot',
            name='pilot_marital_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('UNMARRIED', 'Unmarried')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
