# Generated by Django 3.2 on 2021-05-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20210502_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crewmembers',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundstaff',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilot',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
