# Generated by Django 3.2 on 2021-05-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20210502_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
