# Generated by Django 3.2 on 2021-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_flight_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
