# Generated by Django 3.2 on 2021-05-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_remove_flight_flight_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_delay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
